apiVersion: apps/v1
kind: Deployment
metadata:
  name: movierecommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
      - name: moviers
        image: gcr.io/united-aura-322008/movie_rs
        ports:
        - containerPort: 8501
      